/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package managerGUI;

/**
 *
 * @author Alvaro
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        MostrarPlantilla = new javax.swing.JButton();
        AltaJugador = new javax.swing.JButton();
        AnnadirPartido = new javax.swing.JButton();
        Emeroteca = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Autor = new javax.swing.JLabel();
        Autor1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administracion general ");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jLabel1.setText("Bienvenido al panel de administracion del equipo");

        MostrarPlantilla.setFont(new java.awt.Font("Perpetua", 1, 14)); // NOI18N
        MostrarPlantilla.setText("Mostrar plantilla");
        MostrarPlantilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarPlantillaActionPerformed(evt);
            }
        });

        AltaJugador.setFont(new java.awt.Font("Perpetua", 1, 14)); // NOI18N
        AltaJugador.setText("Alta jugador");
        AltaJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AltaJugadorActionPerformed(evt);
            }
        });

        AnnadirPartido.setFont(new java.awt.Font("Perpetua", 1, 14)); // NOI18N
        AnnadirPartido.setText("Añadir partido");
        AnnadirPartido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnnadirPartidoActionPerformed(evt);
            }
        });

        Emeroteca.setFont(new java.awt.Font("Perpetua", 1, 14)); // NOI18N
        Emeroteca.setText("Hemeroteca");
        Emeroteca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmerotecaActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/managerGUI/dgz.jpeg"))); // NOI18N

        Autor.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        Autor.setText("Autor: Ing.Álvaro Arribas Royo");

        Autor1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        Autor1.setText("Campo de conocimiento: Ciencias de la computación");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Autor1, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Autor, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(132, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AltaJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MostrarPlantilla))
                .addGap(80, 80, 80)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AnnadirPartido, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Emeroteca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MostrarPlantilla, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AnnadirPartido, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AltaJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Emeroteca, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(76, 76, 76)))
                .addComponent(Autor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Autor1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AnnadirPartidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnnadirPartidoActionPerformed
        // TODO add your handling code here:
        AñadirPartido vistaPartido = new AñadirPartido();
        vistaPartido.setVisible(true);
        dispose();
    }//GEN-LAST:event_AnnadirPartidoActionPerformed

    private void MostrarPlantillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarPlantillaActionPerformed
        // TODO add your handling code here:
        MostrarPlantilla vistaPlantilla = new MostrarPlantilla();
        vistaPlantilla.setVisible(true);
        dispose();
    }//GEN-LAST:event_MostrarPlantillaActionPerformed

    private void AltaJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AltaJugadorActionPerformed
        // TODO add your handling code here:
        AltaJugador vistaJugador = new AltaJugador();
        vistaJugador.setVisible(true);
        dispose();
    }//GEN-LAST:event_AltaJugadorActionPerformed

    private void EmerotecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmerotecaActionPerformed
        // TODO add your handling code here:
        Hemeroteca vistaHemeroteca = new Hemeroteca();
        vistaHemeroteca.setVisible(true);
        dispose();
    }//GEN-LAST:event_EmerotecaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AltaJugador;
    private javax.swing.JButton AnnadirPartido;
    private javax.swing.JLabel Autor;
    private javax.swing.JLabel Autor1;
    private javax.swing.JButton Emeroteca;
    private javax.swing.JButton MostrarPlantilla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
